language: csharp
solution: BarcodeReader.sln
install:
  - nuget restore BarcodeReader.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release BarcodeReader.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./BarcodeReader/bin/Release/BarcodeReader.dll
