name: Create packages .NET Framework

on:
  release:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'
          
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
          
      - name: Restore dependencies
        run: msbuild -t:restore
        
      - name: Build
        run: msbuild -t:build --configuration Debug
        
      - name: Test
        run: msbuild -t:test --no-build --verbosity normal

      - name: Pack
        run: msbuild -t:pack --no-build --configuration Debug
        
      - name: Push NuGet
        run: msbuild -t:nuget push "**/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
        
      - name: Push GitHub
        run: nuget.exe push "**/*.nupkg" -NoSymbols -SkipDuplicate
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}
